### ISSUE TITLE
discrepancies for the travis.yml in travis and in crud

### ISSUE THREAD

**Issue by simkimsia** [FriendsOfCake/travis#22]
This is the travis.yml in crud

```
matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1 PHPCS_IGNORE="*/Test/*"

before_script:
  - git clone https://github.com/FriendsOfCake/travis.git --depth 1 ../travis
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

```

This is the same travis.yml found in travis here

```
matrix:
  include:
    - php: 5.4
      env:
        - COVERALLS=1
    - php: 5.4
      env:
        - PHPCS=1
    - php: 5.4
      env:
        - FOC_VALIDATE=1 FOC_TRAVIS=1

before_script:
  - cp -R example_plugin ../example_plugin && cd ../example_plugin
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh
```

May I ask if this is to be expected?
